services:
  db:
    ports:
      - 5454:5432
    container_name: api-forleven
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=